language: ruby
cache: bundler
rvm:
  - 2.1.1
before_script:
  - psql -c 'create database electretri_test;' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
script:
  - RAILS_ENV=test bundle exec rake spec
addons:
  code_climate:
    repo_token: eecc10fc2f909544fb513fb450761bc3a19e437215545cb9d5d91e4c6f689816
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: electretri